- platform: mqtt
  name: "Pir Comedor"
  state_topic: "casa/comedor/pir"
  device_class: motion

- platform: mqtt
  name: "Pir Logia"
  state_topic: "casa/logia/pir"
  device_class: motion

- platform: mqtt
  name: "Pir Escalera"
  state_topic: "casa/escalera/pir"
  device_class: motion

- platform: "mqtt"
  name: "Zigbee Router"
  state_topic: "zigbee2mqtt/router"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.state }}"
  device_class: "connectivity"
  json_attributes: 
    - "linkquality"

- platform: "mqtt"
  name: "Contacto Entrada"
  state_topic: "zigbee2mqtt/contacto_entrada"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"
  json_attributes: 
  - "battery"
  - "voltage"
