- platform: yeelight
  devices:
    172.16.1.21:
      name: Living 1
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    172.16.1.22:
      name: Living 2
      transition: 1000
      use_music_mode: True #(defaults to False)
      save_on_change: False #(defaults to True)
    172.16.1.23:
      name: Porche
- platform: group
  name: Lampara Comedor
  entities:
    - light.living_1
    - light.living_2

