- platform: manual_mqtt
  name: alarma
  code: 1810
  state_topic: casa/alarma
  command_topic: casa/alarma/comando
  trigger_time: 300 #5 minutos
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
  armed_away:
    pending_time: 30
    delay_time: 20
