- platform: manual_mqtt
  name: alarma
  cod: 1810
  state_topic: casa/alarma
  command_topic: casa/alarma/comando
  delay_time: 20
  trigger_time: 300 #5 minutos
  pending_time: 30
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
