- platform: manual_mqtt
  name: alarma
  code: 1810
  state_topic: casa/alarma
  command_topic: casa/alarma/comando
  trigger_time: 300 #5 minutos
  pending_time: 30
  delay_time: 20
  disarmed:
    trigger_time: 0
  armed_home:
    delay_time: 0
    pending_time: 0
