- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
  - icon
  - summary
  - temperature_max
  - temperature_min
  - temperature
  - humidity
  - precip_probability
  update_interal: '00:15'
  language: es

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: memory_use_percent
  - type: processor_use
  - type: since_last_boot
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: load_1m
  - type: load_5m
  - type: load_15m


- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: cert_expiry
  host: !secret host
  name: Lets Encrypt Expiration

- platform: speedtest
  minute:
  - 0
  - 30
  monitored_conditions:
  - ping
  - download
  - upload

- platform: mqtt
  name: Sensor Temperatura
  state_topic: "zigbee2mqtt/sensor_temperatura"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:temperature-celsius"
  value_template: "{{ value_json.temperature }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

- platform: mqtt
  name: Sensor Humedad
  state_topic: "zigbee2mqtt/sensor_temperatura"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

- platform: mqtt
  name: Sensor Presion
  state_topic: "zigbee2mqtt/sensor_temperatura"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  icon: "mdi:blur-radial"
  value_template: "{{ value_json.pressure }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

