- alias: 'Notify - HA Pi Disk Use'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: 65
  action:
    service: notify.ios_iphone_de_cristian
    data:
      title: "Alerta de Sistema"
      message: "HomeAssistant El espacio en disco es muy bajo."

- alias: 'Notify -  HA Pi Disk Use Critical'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: 90
  action:
    service: notify.ios_iphone_de_cristian
    data:
      title: "Alerta de Sistema"
      message: "HomeAssistant El espacio en disco es EXTREMADAMENTE bajo."
